version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: app/.Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: fastapi run

  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
