version: '2.27'

services:
  app:
    build: 
      context: .
      dockerfile: app/.Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
